# Generated by Django 5.0.2 on 2024-05-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='voterid_no',
            field=models.BigIntegerField(max_length=12),
        ),
    ]
