# Generated by Django 5.0.2 on 2024-05-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_alter_complain_voterid_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='voterid_no',
            field=models.BigIntegerField(),
        ),
    ]
